// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xtvoewcowdvayuzettqt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh0dm9ld2Nvd2R2YXl1emV0dHF0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQzNjEyNjYsImV4cCI6MjA1OTkzNzI2Nn0.zE7t1jLCkQf_Tgtl66kLEKVn1pmRbzbUwRGb5mpHqpc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);